### ISSUE TITLE
Query: ActionBar

### ISSUE THREAD

**Issue by jlooper** [jlooper/pocketrave#1]
Is there anything we can do to have buttons in the actionbar variable per page? Normally I would put the ActionBar in each page, but now we have to put it in app.component.tns.html. This causes problems when I need to make buttons vary per page. If not, I have added a workaround with a separate button.

**Comment by NathanWalker** [comment]
I think this was related to something with other funkiness.
Fixed on latest master and actionbar is back on home.component.tns.html where is was originally 👍
