### ISSUE TITLE
SoundCloud integration

### ISSUE THREAD

**Issue by jlooper** [jlooper/pocketrave#2]
We need to prepare this app to allow a user to select a song via SoundCloud on the mobile app and play it on the web. 

The architecture I think would work is to implement a search of SoundCloud using their REST API in the mobile app, and save the id of the selected track to Firebase. It doesn't have to be associated to a particular user, so we don't need auth (everyone will have access to the tracks + images)

In the web app, we will need a list pulled from Firebase of track ids saved from SoundCloud

This issue is to get the REST API working on the mobile side for SoundCloud search, track id saved to Firebase, and tracks listed on the web in some sort of list.

**Comment by jlooper** [comment]
update: the soundcloud service is not in place, and you can query it neatly. There is a bug, and I wonder if you could help me fix it: currently if you input a search value in the search box, you have to tap twice to get the array to populate with results. Could you help me fix this bit? After that, this integration will be pretty nice!

**Comment by NathanWalker** [comment]
I'll look soon 👍
