### ISSUE TITLE
strange behavior of play-pause button layouting in a list!

### ISSUE THREAD

**Issue by jlooper** [jlooper/pocketrave#3]
**Steps to reproduce and a minimal demo of the problem**

run the app, and click 'create'
draw a design on the pad and click 'save'
on the next screen, search for 'soca'. you may need to press return twice (separate bug!)

**Current behavior**

Button background is editable, but button color is not. Right now the background of the button is set to white and the button set to black, but the button doesn't show up at all. If you change the background to 'blue' you just see a blue square without a button.

**Expected/desired behavior**

Um I want to see that button 

The button is fine, outside the listview. I did try removing all CSS, still see this issue. Something is borking the button within the list.

black background, white buttoncolor
![screenshot 2016-08-04 18 37 59](https://cloud.githubusercontent.com/assets/1450004/17420980/425e01fc-5a74-11e6-9ad5-1a7f8ad34cb9.png)
white background, black buttoncolor
![screenshot 2016-08-04 18 47 51](https://cloud.githubusercontent.com/assets/1450004/17420981/43b5f906-5a74-11e6-9e73-cf73b2c343a0.png)

**Comment by NathanWalker** [comment]
Once this PR https://github.com/TheOriginalJosh/nativescript-play-pause-button/pull/6 is merged and a new version released, you will be all set here to allow these to work like this:

![pocketrave](https://cloud.githubusercontent.com/assets/457187/17459283/4ca3668e-5be6-11e6-89b2-805ce6a245fa.gif)

**Comment by TheOriginalJosh** [comment]
I've merged @NathanWalker  and published it. jsut a fyi

**Comment by jlooper** [comment]
terrific!
