### ISSUE TITLE
DrawingPad/ColorSlider

### ISSUE THREAD

**Issue by jlooper** [jlooper/pocketrave#3]
crashes when I navigate to it. Something is wrong with rendering colors I believe. `file:///app/tns_modules/ui/image/image.js:137:28: JS ERROR TypeError: image._setTintColor is not a function. (In 'image._setTintColor(null)', 'image._setTintColor' is undefined)`

**Comment by NathanWalker** [comment]
@jlooper i'm seeing this issue as well in other apps so not sure if this is related to colorslider actually. rc.5 is exhibiting some strange errors like this (with neither of those plugins in use)...
I filed an issue here:
https://github.com/NativeScript/nativescript-angular/issues/422

**Comment by NathanWalker** [comment]
Fixed on master now 👍
