### ISSUE TITLE
colorpicker promise erratic behavior

### ISSUE THREAD

**Issue by jlooper** [jlooper/pocketrave#4]
**Current behavior**
The lovely color picker on iOS seems to behave a little erratically when attempting to set the penColor. The Angular implementation doesn't seem to always set the penColor properly and when it does, you have to choose the color twice to get it to set.
**Expected/desired behavior**
You should be able to use the color picker as designed - pick a color, and the pen changes color.
**Other information**
I believe the way I'm setting up the color picker to use a promise isn't quite right. The problem code is here: 
```
 public selectColor(){
    this.ColorPicker.show('#3489db', 'HEX').then((result:any) => {
      console.log('color int: ' + result);
      this.penColor = result;
    }).catch((err:any) => {
      console.log(err)
    })
  }
```

**Comment by NathanWalker** [comment]
Fixed on latest now with updated plugin 👍
