### ISSUE TITLE
set up listener for firebase and get rave data

### ISSUE THREAD

**Issue by jlooper** [jlooper/pocketrave#5]
Right now I'm able to see data coming into the listener in firebase.service but I have a problem getting it to populate a list. Wondering if you could take a look at:

- components/home/home.component.ts - to see how I should handle this funny Firebase query (you have to set up a listener like we did in Groceries to listen for the data, but not sure with this architecture how to do that)

-services/firebase.service.ts - where should I start the listening routine? Right now I have a subscription set up but it's throwing an error that `'this.firebase.getRaves().subscribe' is undefined)` - I am definitely doing something wrong. I took a look at ShoutOutPlay but I don't see where you set up the OnValueChangeListener as required by the plugin. Moreover this part has to be shred on the web and reused in the 'choose' component.

**Comment by NathanWalker** [comment]
Got something coming here...

**Comment by NathanWalker** [comment]
You will want to:
```
cd nativescript
npm i
```
Before running from root again.

For those that come across this in future, this is how you can achieve the above given multi-platform setup:
```
public getRaves(): Observable<any> {

    return new Observable((observer: any) => {
      let path = 'Raves';
      let listener;

      if (Config.IS_MOBILE_NATIVE()) {

        let onValueEvent = (snapshot) => {
          // console.log("Event type: " + snapshot.type);
          // console.log("Key: " + snapshot.key);
          // console.log("Value: " + JSON.stringify(snapshot.value));
          this.ngZone.run(() => {
            let results = this.handleSnapshot(snapshot.value, path);
            // console.log(`Results: ${results.length}`);
            observer.next(results);
          });
        }

        this.firebase.addValueEventListener(onValueEvent, `/${path}`).then(() => {
          console.log(`firebase listener setup.`);
        });

      } else {

        listener = this.firebase.database().ref(path)
          .on('value', (snapshot:any) => {
            this.ngZone.run(() => {
              observer.next(this.handleSnapshot(snapshot.val(), path));
            });
          }, observer.error);
      }

      return () => {
        // Unsubscribe
        console.log('unsubscribe raves');
        if (Config.IS_MOBILE_NATIVE()) {
          // nothing needs to clean up with native firebase I don't think?
          // may need to check with Eddy, but should be ok for now
        } else {
          // cleanup and detach listener
          this.firebase.database().ref(path).off('value', listener);
        }
      };
    }).share();
  }
```
