### ISSUE TITLE
iPhone 5: unable to change pen size

### ISSUE THREAD

**Issue by NathanWalker** [jlooper/pocketrave#5]
Yes, I still have and use an old iPhone 5s!
Looks like the layout just squishes the slide too tight with the buttons and makes the slider unusable :(

**Comment by NathanWalker** [comment]
![image](https://cloud.githubusercontent.com/assets/457187/18461316/46a49c58-792d-11e6-8e34-c99835d7bb5d.png)

**Comment by jlooper** [comment]
fixed up this screen with a percentage height 👍
